name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username dannyblueman --password dockerpwtest
        docker build . -t konte2022
        docker tag konte2022 dannyblueman/konte2022
        docker push dannyblueman/konte2022
